enum UIState {
  SET_COLUMN,
  SELECT_OBJECT, SPECIFY_OBJECT,
  
  SELECT_AIRFOIL, SELECT_AIRFOIL_SIZE, SELECT_AOA,
  CALIBRATE_X, CALIBRATE_Y,
  
  SELECT_RADIUS,
  
  CONFIRM_OBJECT,
  
  SET_PERIODIC,
  SET_WIND_TUNNEL, SET_WIND_VELOCITY,
  
  SET_LPF, SET_END_LOOP,
  
  SELECT_PAINT,
  SET_CONTOUR, SET_VECTOR_FIELD,
  
  READY,
  RUNNING
}
